// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcxDaO_AvsoyfYQ7IGSJi1v7Z8yocqCg',
    appId: '1:927321111322:web:c5f51696e4ec88c8768aa3',
    messagingSenderId: '927321111322',
    projectId: 'flutter-paint-web-app',
    authDomain: 'flutter-paint-web-app.firebaseapp.com',
    storageBucket: 'flutter-paint-web-app.appspot.com',
    measurementId: 'G-DLN6ERESPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UsI0OnbS3JSN64GHJbYVA09MdjxxvSI',
    appId: '1:927321111322:android:4f9cd8879f5740a5768aa3',
    messagingSenderId: '927321111322',
    projectId: 'flutter-paint-web-app',
    storageBucket: 'flutter-paint-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtqj25vBiZ6RnpdPN8A-d5woqYkym-bOI',
    appId: '1:927321111322:ios:7be5d787e327af67768aa3',
    messagingSenderId: '927321111322',
    projectId: 'flutter-paint-web-app',
    storageBucket: 'flutter-paint-web-app.appspot.com',
    iosClientId: '927321111322-t29evbb2pot41652e3hn5rbkvip7so50.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPaintWebApp',
  );
}
